version: "3.8"

services:
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace:cached
            - ~/.ssh:/home/node/.ssh:ro
        command: sleep infinity
        ports:
            - "3000:3000"
            - "5000:5000"
